# Generated by Django 4.2.4 on 2023-10-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_rating_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('name', 'chef_id')},
        ),
    ]
