# Generated by Django 4.2.4 on 2023-10-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('id', 'recipe')},
        ),
    ]
